##################################################
# Variables
##################################################

SELF_DIR=$(realpath $(dir $(realpath $(lastword $(MAKEFILE_LIST)))))

SOURCE_DIR_2015=$(wildcard $(SELF_DIR)/ir-calcul/sources2015m_4_6/*.m)
SOURCE_DIR_2016=$(wildcard $(SELF_DIR)/ir-calcul/sources2016m_4_5/*.m)
SOURCE_DIR_2017=$(wildcard $(SELF_DIR)/ir-calcul/sources2017m_6_10/*.m)
SOURCE_DIR_2018=$(wildcard $(SELF_DIR)/ir-calcul/sources2018m_6_7/*.m)
SOURCE_DIR_2019=$(wildcard $(SELF_DIR)/ir-calcul/sources2019m_8_0/*.m)
SOURCE_DIR_2020=$(wildcard $(SELF_DIR)/ir-calcul/sources2020m_6_5/*.m)

YEAR?=2020

ifeq ($(YEAR), 2018)
	SOURCE_FILES?=$(SOURCE_DIR_2018)
	MPP_FILE?=$(SELF_DIR)/mpp_specs/2018_6_7.mpp
	TESTS_DIR?=$(SELF_DIR)/tests/2018/fuzzing/
	M_SPEC_FILE?=$(SELF_DIR)/m_specs/complex_case_with_ins_outs_2018.m_spec
else ifeq ($(YEAR), 2019)
	SOURCE_FILES?=$(SOURCE_DIR_2019)
	MPP_FILE?=$(SELF_DIR)/mpp_specs/2019_8_0.mpp
	TESTS_DIR?=$(SELF_DIR)/tests/2019/fuzzing/
	M_SPEC_FILE?=m_specs/complex_case_with_ins_outs_2019.m_spec
else ifeq ($(YEAR), 2020)
	SOURCE_FILES?=$(SOURCE_DIR_2020)
	MPP_FILE?=$(SELF_DIR)/mpp_specs/2020_6_5.mpp
	TESTS_DIR?=$(SELF_DIR)/tests/2020/fuzzing/
	M_SPEC_FILE?=$(SELF_DIR)/m_specs/complex_case_with_ins_outs_2020.m_spec
else
    $(error Unsupported year: $(YEAR))
endif
