(ocamllex mlexer)

(menhir
 (modules mparser)
 (flags --exn-carries-state --explain))

(library
 (public_name mlang.frontend)
 (name m_frontend)
 (flags
  (:standard -open Utils -open M_ir))
 (libraries utils m_ir))

(rule
 (target syntax_messages.ml)
 (deps
  (:parser mparser.mly)
  (:msg mparser.messages))
 (action
  (with-stdout-to
   %{target}
   (run menhir %{parser} --base %{parser} --compile-errors %{msg}))))

(rule
 (target new.messages)
 (deps
  (:parser mparser.mly))
 (action
  (with-stdout-to
   %{target}
   (run menhir %{parser} --base %{parser} --list-errors))))

(rule
 (target updated.messages)
 (deps
  (:parser mparser.mly)
  (:msg mparser.messages))
 (action
  (with-stdout-to
   %{target}
   (run menhir %{parser} --base %{parser} --update-errors %{msg}))))

(rule
 (target mparser.messages.updated)
 (deps
  (:parser mparser.mly)
  (:new new.messages)
  (:updated updated.messages))
 (action
  (with-stdout-to
   %{target}
   (run menhir %{parser} --base %{parser} --merge-errors %{new}
     --merge-errors %{updated}))))

(rule
 (alias runtest)
 (package mlang)
 (deps mparser.messages mparser.messages.updated)
 (action
  (diff mparser.messages mparser.messages.updated)))
