(******************************************************************************)
(*                                                                            *)
(* Droit d'auteur (c) 2026 DGFiP - INRIA                                      *)
(*                                                                            *)
(* Ce programme est distribué sous la licence CeCILL-C: vous pouvez le        *)
(* redistribuer et/ou le modifier sous les contraintes de celle-ci.           *)
(*                                                                            *)
(* L'accessibilité au code source et les droits de copie, de modification et  *)
(* de redistribution qui découlent de ce contrat ont pour contrepartie de     *)
(* n'offrir aux utilisateurs qu'une garantie limitée et de ne faire peser sur *)
(* l'auteur du logiciel, le titulaire des droits patrimoniaux et les          *)
(* concédants successifs qu'une responsabilité restreinte.                    *)
(*                                                                            *)
(******************************************************************************)

(** Parsing error messages handler. The .ml file corresponding to this mli is
    generated automatically generated by menhir from the [syntax.messages] file.
    This file is the core of parsing message handling: this is where all error
    messages must be added. You can either:
    - write the error message directly, which will be output when the parser
      encounters an error;
    - write "Lang:'code'" and add the code to the set of functions in
      {!module M_messages} to be selected by [select_parse_error_message], which
      can handle multiple language messages.

    The structure of the [syntax.messages] strongly depends on the parser's. If
    the parser changes, it may be necessary to rework on it to update the error
    messages. Hopefully, [menhir] comes with a way to automatically update
    messages when the parser changes. This can be automatically done by running
    [dune runtest --auto-promote]. Check the [src/mlang/m_frontend/dune] file
    for more information.

    Each possible error is mapped to a state (an integer) and a custom message
    in the [syntax.messages] file. When the parser raises an exception, it also
    raises the state in which it failed. This module allows to get the
    corresponding error message.

    There is then three possibilities: * the state has a custom error message,
    which can be printed; * the state has the default error message (<"YOUR
    SYNTAX ERROR MESSAGE HERE>"), which has not been customized yet; * the state
    has no error message, which should happen only if the [syntax.messages] is
    not sync with [mparser.mly]. *)

val message : int -> string
(** Returns the error message corresponding to a parser error state. Raises
    [Not_found] if the state has no error message. *)
