val fresh_c_local : string -> string
(** Generates a fresh string that is certain to be different from all strings
    generated by this function (given the initial string has no digits in it).
*)

val generate_variable :
  ?def_flag:bool -> ?trace_flag:bool -> Com.var_space -> Com.Var.t -> string

type dflag = Def | Val | VarInfo | VarSpace

(** {1 Low-level M computation} *)

(** This module distinguish defineness and valuation computations of M
    expressions so they can be expressed independantly and more thoroughtly
    optimized. Definition of such expression follows as such:

    - express the computation of definess and valuation independantly through
      the use of constructors in {!section:constr};
    - sub-expressions can be used to build up the M expression tree (see
      {!expression_composition});
    - the dependency between local variables used throughout the computation by
      delaying their construction within ({!builder});
    - a fully defined expression can be processed into a optimized value that
      can be printed ({!build_expression}) *)

(** {2:constr Expression constructors} *)

(** These are the smart constructors used to build expressions. In effect, they
    represent the language in which computations are defined. *)

(** They are used as traditional nestable sum-type constructors. An example:

    {v 0.5 * (x + y) v}

    would turn into

    {[
      mult (lit 0.5) (plus (local_var x) (local_var y))
    ]}

    where [x] and [y] are previously defined {!local_var}s *)

module DE : Def_expr.S with type expr = Constr.t

val def_expr_to_constr : DE.t -> Constr.t

(** {2 Decoupled expressions} *)

(** While {!constr} is the expression language for decoupled values, the
    following represents complete and optimized expressions for M computations
*)

type expression_composition = {
  set_vars : (dflag * string * Constr.t) list;
  def_test : DE.t;
  value_comp : Constr.t;
}
(** Representation of an M computation in construction. [def_test] for the
    defineness flag, and [value_comp] for the actual valuation. *)

val build_transitive_composition :
  ?safe_def:bool -> expression_composition -> expression_composition
(** Refine an expression composition to enfore M invariants. Mainly the fact
    that undefined value are valuated to zero. [value_comp] of the argument is
    expected to be defined assuming the expression {i is} defined. [safe_def],
    which defaults to [false], can be set when the defined [value_comp]
    computation will evaluate to zero if [def_test] do, allowing the guard to be
    optimized away. *)

val eundefined : unit -> expression_composition
(** The representation of undefined *)

val elit : float -> expression_composition
(** Literals have a simple enough representation they can be written as an
    expression composition without relying on constructions. *)

val comparison :
  Com.comp_op Pos.marked ->
  expression_composition ->
  expression_composition ->
  expression_composition

val binop :
  Com.binop Pos.marked ->
  expression_composition ->
  expression_composition ->
  expression_composition

val unop : Com.unop -> expression_composition -> expression_composition

val conditional :
  expression_composition ->
  expression_composition ->
  expression_composition ->
  expression_composition

val dfun_with_ptr :
  string ->
  (ptrdef:Constr.t -> ptrval:Constr.t -> Constr.t list) ->
  expression_composition
(** [dfun_with_ptr fn args]

    Some functions use pointers to save the definition status & the value of a
    calculation. This function builds the expression composition defining these
    pointers and their position as arguments ([args] serves as a specification
    of how to build the list of arguments). *)

type local_decls
(** Representation of local variables existing in an expression *)

val write_c_expr :
  Dgfip_options.flags ->
  Format.formatter ->
  string ->
  string ->
  expression_composition ->
  unit
(** Crush {!constr} values into closed expressions {!t} *)

val format_local_declarations : Format.formatter -> local_decls -> unit

module Func : sig
  val supzero : expression_composition -> expression_composition

  val present : expression_composition -> expression_composition

  val null : expression_composition -> expression_composition

  val arr : expression_composition -> expression_composition

  val inf : expression_composition -> expression_composition

  val abs : expression_composition -> expression_composition

  val max :
    expression_composition -> expression_composition -> expression_composition

  val min :
    expression_composition -> expression_composition -> expression_composition

  val multimax :
    expression_composition -> Com.Var.t Com.var_id -> expression_composition

  val nb_events : unit -> expression_composition

  val nb_anomalies : unit -> expression_composition

  val nb_discordances : unit -> expression_composition

  val nb_informatives : unit -> expression_composition

  val nb_bloquantes : unit -> expression_composition

  val call : string -> expression_composition list -> expression_composition
end
